version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "strapi-docker"
    REPOSITORY_URI: "471112830029.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-471112830029-us-east-1"
phases:
  pre_build:
    commands:
      - echo "Pre build phase"
      - yarn
      - echo $IMAGE_REPO_NAME
  build:
    commands:
      - echo "Building started on `date`"
      
  post_build:
    commands:
      - echo "Build completed"
      
artifacts:
  files:
    - "**/*"
  discard-paths: yes
