version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "strapi-docker"
    REPOSITORY_URI: "471112830029.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-471112830029-us-east-1"
phases:
  pre_build:
    commands:
      - echo "Pre build phase"
      - echo $IMAGE_REPO_NAME
      - aws ecr get-login-password --region  us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "Building started on `date`"
      - docker build -t $IMAGE_REPO_NAME:latest .
      - echo $IMAGE_REPO_NAME $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - docker push $IMAGE_REPO_NAME $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - "**/*"
  discard-paths: yes
